apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_INSTALL_PLUGINS
              value: grafana-piechart-panel
          volumeMounts:
            - mountPath: /etc/grafana
              name: grafana-config
              readOnly: false
            - mountPath: /grafana-dashboard-definitions/0/veidemann
              name: grafana-dashboards-veidemann
              readOnly: false
            - mountPath: /grafana-dashboard-definitions/0/redis
              name: grafana-dashboards-redis
      volumes:
        - name: grafana-config
          secret:
            secretName: grafana-config
        - configMap:
            name: grafana-dashboards-veidemann
          name: grafana-dashboards-veidemann
        - configMap:
            name: grafana-dashboards-redis
          name: grafana-dashboards-redis
