# pywb config file
# ========================================
#

collections:
  all: $all
  ia: memento+https://web.archive.org/web/
  nb:
    index:
      type: cdx
      api_url: http://gowarc-server:9999/warcserver/all/index?url={url}&closest={timestamp}
      replay_url: http://gowarc-server:9999/warcserver/all/resource?url={url}&closest={timestamp}&output=content

# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true

autoindex: 30

# defaults

#collections_root: collections
#
## Per-Collection Paths
#archive_paths: archive
#index_paths: indexes
#acl_paths: acl
#static_path: static
#
#default_access: allow
#
#templates_dir: templates
#
## Template HTML
#banner_html: banner.html
#head_insert_html: head_insert.html
#frame_insert_html: frame_insert.html
#
#query_html: query.html
#search_html: search.html
#not_found_html: not_found.html
#
#home_html: index.html
#error_html: error.html
#
#proxy_cert_download_html: proxy_cert_download.html
#proxy_select_html: proxy_select.html
#
## Info JSON
#info_json: collinfo.json
#
## HTML Templates List
#html_templates:
#  - banner_html
#  - head_insert_html
#  - frame_insert_html
#
#  - query_html
#  - search_html
#  - not_found_html
#
#  - home_html
#  - error_html
#  - proxy_cert_download_html
#  - proxy_select_html
#
## Other Settings
#enable_memento: true
#
#rules_config: pkg://pywb/rules.yaml
