apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: exporter
  jobLabel: redis
  namespaceSelector:
    matchNames:
    - veidemann
  selector:
    matchLabels:
      redis: distributed-lock
