---
# Source: dex/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.1.0
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: "2.17.0"
    app.kubernetes.io/managed-by: Tiller
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
  - kind: ServiceAccount
    name: dex
    namespace: default