---
# Source: dex/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.1.0
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: "2.17.0"
    app.kubernetes.io/managed-by: Tiller
  name: dex