apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dex-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/dex`)
      kind: Rule
      services:
        - name: dex
          port: 32000
  tls: {}
