kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../../bases/dex
  - ingressroute.yaml

secretGenerator:
  - name: dex
    behavior: replace
    files:
      - config.yaml
