apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: loke-
namespace: veidemann

configurations:
  - kustomize-ingressroute-config.yaml
    
resources:
  - ../../../bases/gowarc-server
  - ../../../bases/pywb
  - ingressroute.yaml

patchesStrategicMerge:
  - deployment_volume_patch.yaml

configMapGenerator:
  - name: pywb-config
    behavior: replace
    files:
      - config.yaml
  - name: nginx-config
    behavior: replace
    files:
      - default.conf
