kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/name: veidemann-reset

resources:
  - job.yaml

images:
  - name: veidemann-reset
    newTag: 0.1.0
    newName: norsknettarkiv/veidemann-reset

secretGenerator:
  - name: veidemann-reset-secrets
    literals:
      - RETHINKDB_PASSWORD=rethinkdb
