apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-health-check-api
spec:
  template:
    spec:
      volumes:
        - name: versions
          configMap:
            name: veidemann-version
            items:
              - key: versions.json
                path: versions.json
      containers:
        - name: veidemann-health-check-api
          env:
            - name: CONTROLLER_HOST
              value: $(CONTROLLER_SERVICE_NAME)
            - name: VEIDEMANN_DASHBOARD_URL
              value: "http://$(DASHBOARD_SERVICE_NAME)/veidemann"
          volumeMounts:
            - mountPath: /versions.json
              subPath: versions.json
              name: versions
