apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bases/veidemann

patchesStrategicMerge:
  - minikube_ip_patch.yaml

patchesJson6902:
  - target:
      kind: Deployment
      name: veidemann-controller
      version: v1
      group: apps
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SKIP_AUTHENTICATION
          value: "false"

configMapGenerator:
  - name: veidemann-version
    behavior: replace
    files:
      - versions.json
