apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - ../../../bases/tensorflow-jupyter
  - ingressroute.yaml
  - jupyter-notebooks-pvc.yaml

patchesStrategicMerge:
  - deployment_volume_patch.yaml
  - deployment_env_patch.yaml

configMapGenerator:
  - name: jupyter-config
    files:
      - jupyter_notebook_config.py
