apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: dex
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: dex-2.1.0
  name: dex
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: main
      $setElementOrder/volumes:
      - name: config
      containers:
      - $setElementOrder/volumeMounts:
        - mountPath: /etc/dex/cfg
        name: main
        volumeMounts:
        - $patch: delete
          mountPath: /etc/dex/tls/https/server
      volumes:
      - $patch: delete
        name: https-tls