apiVersion: batch/v1
kind: Job
metadata:
  name: veidemann-reset
spec:
  # Job is eligible to be deleted immediatly after it is completed
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: veidemann-reset
          envFrom:
            - secretRef:
                name: veidemann-reset-secret
