kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../../bases/veidemann-reset

secretGenerator:
  - name: veidemann-reset-secret
    behavior: replace
    literals:
      - RETHINKDB_PASSWORD=rethinkdb

patchesStrategicMerge:
  - job_ttl_patch.yaml
